#!/usr/bin/env bash
#9-to_file_or_not_to_file
item="school"
if [ -e "$item" ]
then
echo "school file exists"
if [ -s  $item ]
then
echo "school file is not empty"
else
echo "school file is empty"
fi
if [ -f "$item" ]
then
echo "school is a regular file"
fi
else
echo "school file does not exist"
fi
